name:  CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: |
        curl -L -v https://dddyyy01.wioqop.top/api/v1/client/subscribe?token=5cb05ee893a92fd29e39c7ae2832652e
